"""Public facade for product-owned embedding and multimodal boundaries.

Kogwistar owns generic embedding profiles and vector-store primitives.  This
package exposes the LLM-Wiki adapters, source-unit handling, and projection
interfaces without moving the historical modules used by downstream callers.
"""

from ..embedding_config_resolver import (
    EMBEDDING_SPACES,
    TinyEmbeddingFunction,
    embedding_profile,
    resolve_embedding_function,
    resolve_embedding_functions,
    validate_shared_postgres_embedding_profile,
)
from ..multimodal_grounding import (
    EvidenceClosureResolver,
    EvidenceClosureValidator,
    EvidencePack,
    EvidencePackReference,
    GroundingComposition,
    GroundingValidationError,
    HigherOrderGrounding,
    PinnedEntityRef,
    ResolvedEntityGrounding,
    SourceEvidenceRef,
)
from ..multimodal_projection import (
    AssetResolver,
    ChromaMultimodalProjectionStore,
    ColQwenNativeEncoder,
    EmbeddingProfileMismatch,
    EmbeddingSet,
    FakeMultimodalEncoder,
    InMemoryMultimodalProjectionStore,
    MultimodalEmbeddingProfile,
    MultimodalEncoder,
    MultimodalImageQueryEncoder,
    MultimodalProjectionStore,
    MultimodalSearchHit,
    MultimodalSourceUnit,
    ProjectionIntegrityError,
    SQLiteMultimodalProjectionStore,
    embed_pending,
    score_embedding_sets,
)
from ..multimodal_remote import (
    EmbeddingProtocolError,
    EmbeddingServiceError,
    EmbeddingServiceSettings,
    EmbeddingServiceUnavailable,
    RemoteMultimodalEncoder,
)
from ..multimodal_sources import (
    LocalFileAssetResolver,
    MappingAssetResolver,
    MultimodalSourceBundle,
    build_source_bundle,
    manifest_units,
    pdf_manifest_units,
    split_text_units,
    webpage_units,
)
from ..vllm_remote import VllmEmbeddingSettings, VllmMultimodalEncoder

__all__ = [
    "EMBEDDING_SPACES",
    "AssetResolver",
    "ChromaMultimodalProjectionStore",
    "ColQwenNativeEncoder",
    "EmbeddingProfileMismatch",
    "EmbeddingProtocolError",
    "EmbeddingServiceError",
    "EmbeddingServiceSettings",
    "EmbeddingServiceUnavailable",
    "EmbeddingSet",
    "EvidenceClosureResolver",
    "EvidenceClosureValidator",
    "EvidencePack",
    "EvidencePackReference",
    "FakeMultimodalEncoder",
    "GroundingComposition",
    "GroundingValidationError",
    "HigherOrderGrounding",
    "InMemoryMultimodalProjectionStore",
    "LocalFileAssetResolver",
    "MappingAssetResolver",
    "MultimodalEmbeddingProfile",
    "MultimodalEncoder",
    "MultimodalImageQueryEncoder",
    "MultimodalProjectionStore",
    "MultimodalSearchHit",
    "MultimodalSourceBundle",
    "MultimodalSourceUnit",
    "PinnedEntityRef",
    "ProjectionIntegrityError",
    "RemoteMultimodalEncoder",
    "ResolvedEntityGrounding",
    "SQLiteMultimodalProjectionStore",
    "SourceEvidenceRef",
    "TinyEmbeddingFunction",
    "VllmEmbeddingSettings",
    "VllmMultimodalEncoder",
    "build_source_bundle",
    "embed_pending",
    "embedding_profile",
    "manifest_units",
    "pdf_manifest_units",
    "resolve_embedding_function",
    "resolve_embedding_functions",
    "score_embedding_sets",
    "split_text_units",
    "validate_shared_postgres_embedding_profile",
    "webpage_units",
]
