"""Static contract shared by the gateway's cooperative mixins."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol, TypeAlias

from kogwistar.json_types import JsonValue

from ..models import IngestPipelineRequest
from ..otel import LlmWikiTelemetry
from ..workbench.workbench_api import WorkbenchApi

ToolArguments: TypeAlias = Mapping[str, JsonValue]
JsonObject = dict[str, JsonValue]


class AgentGatewayHost(Protocol):
    """Attributes and handlers supplied by the composed gateway facade.

    The production class implements these members across several mixins.  The
    protocol keeps each mixin type-checkable without creating a second runtime
    base class or duplicating gateway behavior.
    """

    api: WorkbenchApi
    telemetry: LlmWikiTelemetry

    def _answer(self, payload: Mapping[str, JsonValue]) -> JsonObject: ...

    def _source_documents(self, workspace_id: str) -> Sequence[JsonObject]: ...

    def _source_ids_for_topic(
        self,
        workspace_id: str,
        topic: str,
        *,
        candidates: Sequence[JsonObject] | None = None,
    ) -> list[str]: ...

    def _load_source_request(
        self,
        *,
        workspace_id: str,
        source_uri: str = "",
        source_document_id: str = "",
        candidates: Sequence[JsonObject] | None = None,
    ) -> IngestPipelineRequest | None: ...

    def _load_source_request_by_id(
        self,
        *,
        workspace_id: str,
        source_document_id: str,
    ) -> IngestPipelineRequest | None: ...

    def query(self, arguments: ToolArguments) -> JsonObject: ...
    def search(self, arguments: ToolArguments) -> JsonObject: ...
    def ingest(self, arguments: ToolArguments) -> JsonObject: ...
    def source(self, arguments: ToolArguments) -> JsonObject: ...
    def reingest(self, arguments: ToolArguments) -> JsonObject: ...
    def maintain(self, arguments: ToolArguments) -> JsonObject: ...
    def status(self, arguments: ToolArguments) -> JsonObject: ...
    def hypergraph_search(self, arguments: ToolArguments) -> JsonObject: ...
    def history(self, arguments: ToolArguments) -> JsonObject: ...
    def memory_recall(self, arguments: ToolArguments) -> JsonObject: ...
    def memory_capture(self, arguments: ToolArguments) -> JsonObject: ...
    def memory_review(self, arguments: ToolArguments) -> JsonObject: ...
    def multimodal_capture(self, arguments: ToolArguments) -> JsonObject: ...
    def multimodal_index(self, arguments: ToolArguments) -> JsonObject: ...
    def multimodal_search(self, arguments: ToolArguments) -> JsonObject: ...
    def multimodal_status(self, arguments: ToolArguments) -> JsonObject: ...
    def propose(self, arguments: ToolArguments) -> JsonObject: ...
    def confirm(self, arguments: ToolArguments) -> JsonObject: ...
