"""Static contract shared by the gateway's cooperative mixins."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol

from ..models import IngestPipelineRequest
from ..otel import LlmWikiTelemetry
from ..workbench.workbench_api import WorkbenchApi

type ToolArguments = Mapping[str, object]


class AgentGatewayHost(Protocol):
    """Attributes and handlers supplied by the composed gateway facade.

    The production class implements these members across several mixins.  The
    protocol keeps each mixin type-checkable without creating a second runtime
    base class or duplicating gateway behavior.
    """

    api: WorkbenchApi
    telemetry: LlmWikiTelemetry

    def _answer(self, payload: Mapping[str, object]) -> dict[str, object]: ...

    def _source_documents(self, workspace_id: str) -> Sequence[Mapping[str, object]]: ...

    def _source_ids_for_topic(
        self,
        workspace_id: str,
        topic: str,
        *,
        candidates: Sequence[Mapping[str, object]] | None = None,
    ) -> list[str]: ...

    def _load_source_request(
        self,
        *,
        workspace_id: str,
        source_uri: str = "",
        source_document_id: str = "",
        candidates: Sequence[Mapping[str, object]] | None = None,
    ) -> IngestPipelineRequest | None: ...

    def _load_source_request_by_id(
        self,
        *,
        workspace_id: str,
        source_document_id: str,
    ) -> IngestPipelineRequest | None: ...

    def query(self, arguments: ToolArguments) -> dict[str, object]: ...
    def search(self, arguments: ToolArguments) -> dict[str, object]: ...
    def ingest(self, arguments: ToolArguments) -> dict[str, object]: ...
    def source(self, arguments: ToolArguments) -> dict[str, object]: ...
    def reingest(self, arguments: ToolArguments) -> dict[str, object]: ...
    def maintain(self, arguments: ToolArguments) -> dict[str, object]: ...
    def status(self, arguments: ToolArguments) -> dict[str, object]: ...
    def hypergraph_search(self, arguments: ToolArguments) -> dict[str, object]: ...
    def history(self, arguments: ToolArguments) -> dict[str, object]: ...
    def memory_recall(self, arguments: ToolArguments) -> dict[str, object]: ...
    def memory_capture(self, arguments: ToolArguments) -> dict[str, object]: ...
    def memory_review(self, arguments: ToolArguments) -> dict[str, object]: ...
    def multimodal_capture(self, arguments: ToolArguments) -> dict[str, object]: ...
    def multimodal_index(self, arguments: ToolArguments) -> dict[str, object]: ...
    def multimodal_search(self, arguments: ToolArguments) -> dict[str, object]: ...
    def multimodal_status(self, arguments: ToolArguments) -> dict[str, object]: ...
    def propose(self, arguments: ToolArguments) -> dict[str, object]: ...
    def confirm(self, arguments: ToolArguments) -> dict[str, object]: ...
